version: '3.8'

services:
  app_blue:
    image: ${BLUE_IMAGE}
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - APP_POOL=blue
    ports:
      - "8081:3000"
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:3000/healthz', res => process.exit(res.statusCode===200?0:1))\""]
      interval: 3s
      timeout: 3s        # increased from 1s
      retries: 3
      start_period: 5s   # increased from 2s
    restart: always

  app_green:
    image: ${GREEN_IMAGE}
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - APP_POOL=green
    ports:
      - "8082:3000"
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:3000/healthz', res => process.exit(res.statusCode===200?0:1))\""]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: always

  nginx:
    image: nginx:1.25
    depends_on:
      app_blue:
        condition: service_healthy
      app_green:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - ./nginx/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    restart: always
